#!/bin/bash
# ============================================================================
# Playwright MCP Project Setup
# ============================================================================
#
# Reads your projects file and generates all configs automatically.
#
# Usage:
#   ./setup.sh                     # uses ./projects.conf
#   ./setup.sh ~/my-projects.conf  # custom path
#
# What it does:
#   1. Reads your project definitions (name | account | directories)
#   2. Generates ~/.claude/chrome-profiles.json
#   3. Installs the launcher script
#   4. Registers MCP in Claude Code via `claude mcp add`
#   5. Creates Chrome user-data directories
#
# ============================================================================

set -e

CONFIG_FILE="${1:-projects.conf}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}╔══════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  Playwright MCP Project Setup            ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════╝${NC}"
echo

# ── Check config file ──────────────────────────────────────────────
if [ ! -f "$CONFIG_FILE" ]; then
  echo -e "${RED}Config file not found: $CONFIG_FILE${NC}"
  echo
  echo "Create it from the example:"
  echo "  cp projects.example projects.conf"
  echo "  # edit projects.conf with your projects"
  echo "  ./setup.sh"
  exit 1
fi

# ── Check claude CLI ─────────────────────────────────────────────
if ! command -v claude &>/dev/null; then
  echo -e "${RED}claude CLI not found. Install Claude Code first.${NC}"
  exit 1
fi

echo -e "${GREEN}Reading:${NC} $CONFIG_FILE"
echo

# ── Parse projects + generate configs ────────────────────────────
SETUP_CONFIG_FILE="$CONFIG_FILE" SETUP_SCRIPT_DIR="$SCRIPT_DIR" python3 << 'PYTHON_SCRIPT'
import os, json, glob, shutil, subprocess

config_file = os.environ["SETUP_CONFIG_FILE"]
script_dir = os.environ["SETUP_SCRIPT_DIR"]
home = os.path.expanduser("~")
claude_dir = os.path.join(home, ".claude")

# Parse config
projects = []
with open(config_file) as f:
    for line in f:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split("|")]
        if len(parts) != 3:
            print(f"  Warning: skipping malformed line: {line}")
            continue
        name, account, dirs_str = parts
        dirs = []
        for d in dirs_str.split():
            expanded = os.path.expanduser(d)
            if "*" in expanded:
                matches = sorted(glob.glob(expanded))
                dirs.extend([m for m in matches if os.path.isdir(m)])
            else:
                if os.path.isdir(expanded):
                    dirs.append(expanded)
                else:
                    print(f"  Warning: directory not found: {expanded}")
                    dirs.append(expanded)
        projects.append({
            "name": name,
            "account": None if account.lower() == "clean" else account,
            "dirs": dirs
        })

if not projects:
    print("Error: no projects found in config file!")
    exit(1)

print(f"Found {len(projects)} projects:\n")

# ── Assign ports ───────────────────────────────────────────────────
base_port = 9223
for i, p in enumerate(projects):
    p["port"] = base_port + i
    p["userDataDir"] = os.path.join(home, f".chrome-pw-{p['name']}")
    account_str = p["account"] or "(clean browser)"
    print(f"  {p['name']:15s} port {p['port']}, {account_str}")
    for d in p["dirs"]:
        print(f"                    {d}")
    print()

# ── Generate chrome-profiles.json ──────────────────────────────────
profiles_data = {
    "default": projects[0]["name"],
    "profiles": {}
}
for p in projects:
    profiles_data["profiles"][p["name"]] = {
        "port": p["port"],
        "userDataDir": p["userDataDir"].replace(home, "~"),
        "account": p["account"],
        "note": "Auto-generated by setup.sh"
    }

profiles_path = os.path.join(claude_dir, "chrome-profiles.json")
os.makedirs(claude_dir, exist_ok=True)
with open(profiles_path, "w") as f:
    json.dump(profiles_data, f, indent=2, ensure_ascii=False)
print(f"OK: {profiles_path}")

# ── Install launcher script ────────────────────────────────────────
scripts_dir = os.path.join(claude_dir, "scripts")
os.makedirs(scripts_dir, exist_ok=True)
src = os.path.join(script_dir, "scripts", "playwright-project.sh")
dst = os.path.join(scripts_dir, "playwright-project.sh")
shutil.copy2(src, dst)
os.chmod(dst, 0o755)
print(f"OK: {dst}")

# ── Register MCP via claude CLI ──────────────────────────────────
# User-scope default (fallback for unregistered directories)
default_name = projects[0]["name"]
subprocess.run(
    ["claude", "mcp", "add", "-s", "user", "playwright", "--", dst],
    capture_output=True
)
print(f"OK: registered user-scope default (profile: {default_name})")

# Per-directory local-scope registrations
reg_count = 0
for p in projects:
    for d in p["dirs"]:
        abs_path = os.path.abspath(d)
        if not os.path.isdir(abs_path):
            continue
        result = subprocess.run(
            ["claude", "mcp", "add", "-s", "local", "playwright", "--", dst, p["name"]],
            capture_output=True, cwd=abs_path
        )
        if result.returncode == 0:
            reg_count += 1
        else:
            print(f"  Warning: failed to register {abs_path}")

print(f"OK: registered {reg_count} directory bindings")

# ── Create user-data-dirs ──────────────────────────────────────────
for p in projects:
    os.makedirs(p["userDataDir"], exist_ok=True)

# ── Summary ────────────────────────────────────────────────────────
print()
print("=" * 50)
print("SETUP COMPLETE")
print("=" * 50)
print()
print("Next steps:")
for p in projects:
    if p["account"]:
        print(f'  1. Start Claude Code from a {p["name"]} directory')
        print(f'  2. Log in to {p["account"]} in the Chrome window that opens')
        print()
    else:
        print(f'  "{p["name"]}" uses a clean browser, no login needed')
        print()

print("Restart Claude Code to apply changes (not just /mcp)")
print()
PYTHON_SCRIPT
