#!/bin/bash
# ============================================================================
# Playwright MCP Project Setup
# ============================================================================
#
# Reads your projects file and generates all configs automatically.
#
# Usage:
#   ./setup.sh                     # uses ./projects.conf
#   ./setup.sh ~/my-projects.conf  # custom path
#
# What it does:
#   1. Reads your project definitions (name | account | directories)
#   2. Generates ~/.claude/chrome-profiles.json
#   3. Generates project-level settings for each directory
#   4. Installs the launcher script
#   5. Updates ~/.claude/settings.json (if confirmed)
#
# ============================================================================

set -e

CONFIG_FILE="${1:-projects.conf}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}╔══════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  Playwright MCP Project Setup            ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════╝${NC}"
echo

# ── Check config file ──────────────────────────────────────────────
if [ ! -f "$CONFIG_FILE" ]; then
  echo -e "${RED}Config file not found: $CONFIG_FILE${NC}"
  echo
  echo "Create it from the example:"
  echo "  cp projects.example projects.conf"
  echo "  # edit projects.conf with your projects"
  echo "  ./setup.sh"
  exit 1
fi

echo -e "${GREEN}Reading:${NC} $CONFIG_FILE"
echo

# ── Parse projects ─────────────────────────────────────────────────
# Uses Python for reliable parsing + glob expansion + JSON generation
SETUP_CONFIG_FILE="$CONFIG_FILE" SETUP_SCRIPT_DIR="$SCRIPT_DIR" python3 << 'PYTHON_SCRIPT'
import os, json, glob, shutil

config_file = os.environ["SETUP_CONFIG_FILE"]
script_dir = os.environ["SETUP_SCRIPT_DIR"]
home = os.path.expanduser("~")
claude_dir = os.path.join(home, ".claude")

# Parse config
projects = []
with open(config_file) as f:
    for line in f:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split("|")]
        if len(parts) != 3:
            print(f"  ⚠ Skipping malformed line: {line}")
            continue
        name, account, dirs_str = parts
        dirs = []
        for d in dirs_str.split():
            expanded = os.path.expanduser(d)
            if "*" in expanded:
                matches = sorted(glob.glob(expanded))
                dirs.extend([m for m in matches if os.path.isdir(m)])
            else:
                if os.path.isdir(expanded):
                    dirs.append(expanded)
                else:
                    print(f"  ⚠ Directory not found (will create on first use): {expanded}")
                    dirs.append(expanded)
        projects.append({
            "name": name,
            "account": None if account.lower() == "clean" else account,
            "dirs": dirs
        })

if not projects:
    print("❌ No projects found in config file!")
    sys.exit(1)

print(f"Found {len(projects)} projects:\n")

# ── Assign ports ───────────────────────────────────────────────────
base_port = 9223
for i, p in enumerate(projects):
    p["port"] = base_port + i
    p["userDataDir"] = os.path.join(home, f".chrome-pw-{p['name']}")
    account_str = p["account"] or "(clean browser)"
    print(f"  {p['name']:15s} → port {p['port']}, {account_str}")
    for d in p["dirs"]:
        print(f"                    📁 {d}")
    print()

# ── Generate chrome-profiles.json ──────────────────────────────────
profiles_data = {
    "default": projects[0]["name"],
    "profiles": {}
}
for p in projects:
    profiles_data["profiles"][p["name"]] = {
        "port": p["port"],
        "userDataDir": p["userDataDir"].replace(home, "~"),
        "account": p["account"],
        "note": f"Auto-generated by setup.sh"
    }

profiles_path = os.path.join(claude_dir, "chrome-profiles.json")
os.makedirs(claude_dir, exist_ok=True)
with open(profiles_path, "w") as f:
    json.dump(profiles_data, f, indent=2, ensure_ascii=False)
print(f"✅ Generated: {profiles_path}")

# ── Install launcher script ────────────────────────────────────────
scripts_dir = os.path.join(claude_dir, "scripts")
os.makedirs(scripts_dir, exist_ok=True)
src = os.path.join(script_dir, "scripts", "playwright-project.sh")
dst = os.path.join(scripts_dir, "playwright-project.sh")
shutil.copy2(src, dst)
os.chmod(dst, 0o755)
print(f"✅ Installed: {dst}")

# ── Generate project-level settings ────────────────────────────────
projects_dir = os.path.join(claude_dir, "projects")
settings_count = 0

for p in projects:
    for d in p["dirs"]:
        # Encode path: /Users/vova/foo → -Users-vova-foo
        abs_path = os.path.abspath(d)
        encoded = abs_path.replace("/", "-")
        project_settings_dir = os.path.join(projects_dir, encoded)
        os.makedirs(project_settings_dir, exist_ok=True)

        settings_path = os.path.join(project_settings_dir, "settings.json")
        settings_data = {
            "mcpServers": {
                "playwright": {
                    "command": dst,
                    "args": [p["name"]]
                }
            }
        }

        with open(settings_path, "w") as f:
            json.dump(settings_data, f, indent=2)
        settings_count += 1

print(f"✅ Generated: {settings_count} project-level settings")

# ── Update global settings.json ────────────────────────────────────
global_settings_path = os.path.join(claude_dir, "settings.json")
default_project = projects[0]["name"]

if os.path.exists(global_settings_path):
    with open(global_settings_path) as f:
        global_settings = json.load(f)

    if "mcpServers" not in global_settings:
        global_settings["mcpServers"] = {}

    global_settings["mcpServers"]["playwright"] = {
        "command": dst,
        "args": [default_project]
    }

    with open(global_settings_path, "w") as f:
        json.dump(global_settings, f, indent=2)
    print(f"✅ Updated: {global_settings_path} (default: {default_project})")
else:
    settings = {
        "mcpServers": {
            "playwright": {
                "command": dst,
                "args": [default_project]
            }
        }
    }
    with open(global_settings_path, "w") as f:
        json.dump(settings, f, indent=2)
    print(f"✅ Created: {global_settings_path} (default: {default_project})")

# ── Create user-data-dirs ──────────────────────────────────────────
for p in projects:
    os.makedirs(p["userDataDir"], exist_ok=True)

# ── Check plugin override ─────────────────────────────────────────
plugin_path = os.path.join(
    claude_dir,
    "plugins/marketplaces/claude-plugins-official/external_plugins/playwright/.mcp.json"
)
if os.path.exists(plugin_path):
    with open(plugin_path) as f:
        content = f.read().strip()
    if content != "{}":
        with open(plugin_path, "w") as f:
            f.write("{}\n")
        print(f"⚠️  Fixed plugin override: {plugin_path} (was not empty, reset to {{}})")

# ── Summary ────────────────────────────────────────────────────────
print()
print("=" * 50)
print("SETUP COMPLETE")
print("=" * 50)
print()
print("Next steps:")
for p in projects:
    if p["account"]:
        print(f'  • Log in to {p["account"]} in Chrome for "{p["name"]}":')
        print(f'    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" \\')
        print(f'      --remote-debugging-port={p["port"]} \\')
        print(f'      --user-data-dir="{p["userDataDir"]}"')
        print()
    else:
        print(f'  • "{p["name"]}" uses a clean browser — no login needed')
        print()

print("Then restart MCP in Claude Code: /mcp")
print()
PYTHON_SCRIPT
